### PR TITLE
Fixed background clearing

### PR DESCRIPTION
**Pull request by crr0004**
Noticed that on Fedora 21, using Gnome Terminal that the background didn't clear properly. Resetting the background color and then calling clear seemed to work. It does need testing on other systems though.

### CODE REVIEW

**Comment by zzggbb** [comment]
does `tput reset` work as a method for clearing the screen and restoring background color?

**Comment by crr0004** [comment]
Yes it does

**Comment by zzggbb** [comment]
fixed: https://github.com/zzggbb/colorblocks/commit/ec888a0e47e482adcbbce9d50b265f7862cafa13
thanks for pointing this out : )

**Comment by crr0004** [comment]
No worries. I'll close this off now

**Pull request closed without merging**
